components/kanban_board_ui/config/routes.rb
KanbanBoardUi::Engine.routes.draw do
  resources :projects do
  	resources :tasks
  	resources :assignments, only: [:update]
    resources :members
  end
  root to: 'projects#index'
end

components/kanban_board_ui/app/controllers/kanban_board_ui/application_controller.rb
module KanbanBoardUi
  class ApplicationController < ::ApplicationController
  end
end

components/kanban_board_ui/app/controllers/kanban_board_ui/assignments_controller.rb
require_dependency "kanban_board_ui/application_controller"

module KanbanBoardUi
  class AssignmentsController < ApplicationController
    before_filter :authenticate_user!

  	def update
  		@assignment = KanbanBoard::Assignment.find(params[:id])
      authorize! :update, @assignment
  		@project = @assignment.project
      respond_to do |format|
        if @assignment.update(assignment_params)
          format.html { redirect_to project_path(@project), notice: 'Task was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    end

    private
    def assignment_params
      params.require(:assignment).permit(:status)
    end

  end
end

components/kanban_board_ui/app/controllers/kanban_board_ui/members_controller.rb
require_dependency "kanban_board_ui/application_controller"

module KanbanBoardUi
  class MembersController < ApplicationController
    before_filter :authenticate_user!
    before_action :set_project
    before_action :authorize_project_owner, only: [:create, :update, :destroy]
    before_action :set_member, only: [:update, :destroy]
    before_action :set_index_values, only: [:index]
    
    def index
      authorize! :read, @project
      @member = @project.members.new
    end

    def create
      @member = @project.members.new(member_params)

      respond_to do |format|
        if @member.save
          format.html { redirect_to project_members_path(@project), notice: 'Member was successfully added.' }
          format.json { render action: 'index', status: :created, location: @member }
        else
          set_index_values
          format.html { render action: 'index' }
          format.json { render json: @member.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @member.update(member_params)
          format.html { redirect_to project_members_path(@project), notice: 'Member was successfully updated.' }
          format.json { head :no_content }
        else
          set_index_values
          format.html { render action: 'index' }
          format.json { render json: @member.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @member.destroy
      respond_to do |format|
        format.html { redirect_to project_members_path(@project) }
        format.json { head :no_content }
      end
    end

    private

    def member_params
      params.require(:member).permit(:user_id, :user_role)
    end

    def set_member
      @member = @project.members.find(params[:id])
    end

    def set_project
      @project = KanbanBoard::Project.includes(:members).find(params[:project_id])
    end

    def set_index_values
      @project_user_ids = @project.users.pluck(:id)
      @users = KanbanBoard.user_class.all
      @members = @project.members.includes(:user)
      @roles = KanbanBoard::Member.roles
    end

    def authorize_project_owner
      authorize! :manage, @project
    end
  end
end

components/kanban_board_ui/app/controllers/kanban_board_ui/projects_controller.rb
require_dependency "kanban_board_ui/application_controller"

module KanbanBoardUi
  class ProjectsController < ApplicationController
    before_filter :authenticate_user!
    before_action :set_project, only: [:show, :edit, :update, :destroy]
    before_action :authorize_project_owner, only: [:edit, :update, :destroy]

    def index
      @projects = current_user.projects.all
    end

    def show
      authorize! :read, @project
      @assignments = KanbanBoard::Assignment.includes(:task, :user).where(project_id: params[:id]).group_by(&:status)
      @owner = @project.owners.first
      @states = KanbanBoard.states
    end

    def new
      @project = KanbanBoard::Project.new
    end

    def edit
    end

    def create
      @project = KanbanBoard::Project.new(project_params)
      respond_to do |format|
        if @project.save
          @project.members.create!(user: current_user, user_role: 'admin')
          format.html { redirect_to @project, notice: 'Project was successfully created.' }
          format.json { render action: 'show', status: :created, location: @project }
        else
          format.html { render action: 'new' }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @project.update(project_params)
          format.html { redirect_to @project, notice: 'Project was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @project.destroy
      respond_to do |format|
        format.html { redirect_to projects_path }
        format.json { head :no_content }
      end
    end

    private
    def set_project
      @project = KanbanBoard::Project.includes(:users).find(params[:id])
    end

    def project_params
      params.require(:project).permit(:title, :description, :deadline)
    end

    def authorize_project_owner
      authorize! :manage, @project
    end
  end
end

components/kanban_board_ui/app/controllers/kanban_board_ui/tasks_controller.rb
require_dependency "kanban_board_ui/application_controller"

module KanbanBoardUi
  class TasksController < ApplicationController
    before_filter :authenticate_user!

    before_action :set_project
    before_action :authorize_project_member, only: [:index, :show]
    before_action :authorize_project_owner, only: [:new, :edit, :create, :update, :destroy]
    before_action :set_task, only: [:show, :edit, :update, :destroy]
    before_action :set_project_members, only: [:new, :edit]

    def index
      @tasks = @project.tasks.all
    end

    def show
    end

    def new
      @task = @project.tasks.new
    end

    def edit
    end

    def create
      @task = @project.tasks.new(task_params)

      respond_to do |format|
        if @task.save
          @task.assignment.update(task_params[:assignment_attributes])
          format.html { redirect_to project_path(@project), notice: 'Task was successfully created.' }
          format.json { render action: 'show', status: :created, location: @task }
        else
          set_project_members
          format.html { render action: 'new' }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      if params[:task][:assignment_attributes]
        @task.assignment.update(task_params[:assignment_attributes])
        params[:task].delete(:assignment_attributes)
      end

      respond_to do |format|
        if @task.update(task_params)
          format.html { redirect_to project_path(@project), notice: 'Task was successfully updated.' }
          format.json { head :no_content }
        else
          set_project_members
          format.html { render action: 'edit' }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @task.destroy
      respond_to do |format|
        format.html { redirect_to project_tasks_url, notice: 'Task was successfully deleted.' }
        format.json { head :no_content }
      end
    end

    private

    def task_params
      params.require(:task).permit(:name, :description, :finishing_date, :priority, assignment_attributes: [:user_id])
    end

    def set_task
      @task = @project.tasks.find(params[:id])
    end

    def set_project
      @project = KanbanBoard::Project.includes(:tasks, :users).find(params[:project_id])
    end

    def set_project_members
      @members = @project.users.all
    end

    def authorize_project_owner
      authorize! :manage, @project
    end

    def authorize_project_member
      authorize! :read, @project
    end
  end
end

components/kanban_board_ui/app/helpers/kanban_board_ui/application_helper.rb
module KanbanBoardUi
  module ApplicationHelper
  end
end

components/kanban_board_ui/app/helpers/kanban_board_ui/assignments_helper.rb
module KanbanBoardUi
  module AssignmentsHelper
  end
end

components/kanban_board_ui/app/helpers/kanban_board_ui/members_helper.rb
module KanbanBoardUi
  module MembersHelper
  end
end

components/kanban_board_ui/app/helpers/kanban_board_ui/project_helper.rb
module KanbanBoardUi
  module ProjectHelper
  end
end

components/kanban_board_ui/app/helpers/kanban_board_ui/tasks_helper.rb
module KanbanBoardUi
  module TasksHelper
  end
end

components/kanban_board_ui/app/views/kanban_board_ui/projects/_form.html.erb
<%= form_for(@project, html: { class: 'form-horizontal' }) do |f| %>
  <% if @project.errors.any? %>
     <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4><%= pluralize(@project.errors.count, "error") %> prohibited this Project from being saved:</h4>
      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :deadline, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.date_field :deadline, min: Date.today, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

components/kanban_board_ui/app/views/kanban_board_ui/projects/edit.html.erb
<h2>Editing project: <%= @project.name %></h2>
<hr>

<%= render 'form' %>
<hr>

<%= link_to 'Back', project_path(@project), class: "btn btn-default pull-right" %>

components/kanban_board_ui/app/views/kanban_board_ui/projects/index.html.erb
<h2>Listing Projects</h2>
<hr>
<% if @projects.empty? %>
	<div class="alert alert-info" role="alert">
		<p>No projects available!</p>
		<%= link_to "Create new project", new_project_path, class: 'btn btn-success' %>
	</div>
<% else %>
<table class="table table-striped">
	<thead>
		<tr>
			<th>#</th>
			<th>Title</th>
			<th>Description</th>
			<th>Deadline</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @projects.each_with_index do |project, index| %>
			<tr>
				<td><%= index+1 %></td>
				<td><%= project.name %></td>
				<td><%= truncate(project.description) if project.description %></td>
				<td><%= project.finishing_date %></td>
				<td><%= link_to 'Show', project, class: 'btn btn-primary btn-xs' %></td>
				<% if can? :manage, project %>
				<td><%= link_to 'Edit', edit_project_path(project), class: 'btn btn-success btn-xs' %></td>
				<td><%= link_to 'Destroy', project, data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-danger btn-xs' %></td>
				<% else %>
					<td></td>
					<td></td>
				<% end %>
			</tr>
		<% end %>
	</tbody>
</table>
<% end %>

components/kanban_board_ui/app/views/kanban_board_ui/projects/new.html.erb
<h2>Add new project</h2>
<hr>

<%= render 'form' %>
<hr>
<%= link_to 'Back', projects_path, class: "btn btn-default pull-right" %>

components/kanban_board_ui/app/views/kanban_board_ui/projects/show.html.erb
<h2><%= @project.name %></h2>
<hr>

<table class="table">
	<thead>
		<tr>
			<% @states.each do |state| %>
				<th><%= state %></th>
			<% end %>
		</tr>
	</thead>
	<tbody>
		<tr>
			<% @states.each_with_index do |state, index| %>
				<td>
					<% if @assignments[state] %>
						<% @assignments[state].each do |a| %>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4><%= link_to a.task.name, project_task_path(@project, a.task) %></h4>
								</div>
								<div class="panel-body">
									<p><strong>Deadline:</strong> <%= a.task.finishing_date %></p>
									<% if a.user_id %>
									<p><strong>User:</strong> <%= a.user.full_name %></p>
									<% end %>
									<p><%= truncate(a.task.description) if a.task.description %></p>
									<% if can?(:update, a) && state != @states.first %>
									<%= link_to content_tag(:span, nil, class: "glyphicon glyphicon-chevron-left pull-left"), project_assignment_path(@project, a, assignment: { status: @states[index-1]}), method: :put, confirm: "Are you sure?" %>
									<% end %>
									<% if can?(:update, a) && state != @states.last %>
									<%= link_to content_tag(:span, nil, class: "glyphicon glyphicon-chevron-right pull-right"), project_assignment_path(@project, a, assignment: { status: @states[index+1]}), method: :put, confirm: "Are you sure?" %>
									<% end %>
								</div>
							</div>
						<% end %>
					<% end %>
				</td>
			<% end %>
		</tr>
	</tbody>
</table>
<div class="alert alert-info">
	<p><strong>Owner:</strong> <%= @owner.full_name %></p>
	<p><strong>Deadline:</strong> <%= @project.deadline %></p>
	<p class="text-muted"><%= @project.description %></p>
</div>
<% if can? :manage, @project %>
	<%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-success pull-right' %>
	<%= link_to 'Add Card', new_project_task_path(@project), class: 'btn btn-primary pull-right' %>
<% end %>
<%= link_to 'Members', project_members_path(@project), class: 'btn btn-primary pull-left' %>